# Default values for web-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: securityunion/nextjs-demo ##this is a test docker image we are pulling from docker hub
  pullPolicy: Always ## means that it will always check for the new version on each restart
  tag: "" ## tag information will be taken from Charts.yaml => appVersion field.

nameOverride: ""
fullnameOverride: ""

service:         # defining node to expose service to outside world
  type: NodePort 
  port: 4444

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: my-website.local
      path: /

resources: {}
